name: CICD Build Pipeline
run-name: CICD Build invoked for ${{ github.event.client_payload.repository }}

on:
  repository_dispatch:
    types: [trigger-cicd-test]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Print workflow metadata
        run: |
          echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
          echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
          echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Display the github object
        run: |
          echo GitHub event object is...
          cat <<EOF
          ${{ toJSON(github) }}
          EOF

      - name: Check out repository code
        uses: actions/checkout@v5
        with:
          repository: ${{ github.event.client_payload.repository }}
          ref: ${{ github.event.client_payload.sha }}

      - name: List directory contents
        run: tree
      - name: List the environment
        run: env

      - name: Perform iat
        run: make cicd_test

      - name: Deliver snapshot
        if: ${{ github.event.client_payload.deliver }} == 'true'
        run: make cicd_deliver_release

      - run: echo "ğŸ This job's status is ${{ job.status }}."

